FROM ubuntu:16.04

LABEL maintainer="Jan Prach <jendap@google.com>"

# Copy and run the install scripts.
COPY install/*.sh /install/
RUN /install/install_bootstrap_deb_packages.sh
RUN add-apt-repository -y ppa:openjdk-r/ppa && \
    add-apt-repository -y ppa:george-edison55/cmake-3.x
RUN /install/install_deb_packages.sh

RUN /install/install_bazel.sh

# TODO see for rest of lines: ~/src/watermeter/tf/non_k8s/meter_reader/build/tensorflow__ssh_back/tensorflow/tensorflow/tools/ci_build/Dockerfile.pi-python3